//! # Tablet Drivers and Parsing
//!
//! This module handles the detection of HID devices, loading of JSON tablet configurations,
//! device initialization sequences, and the parsing of proprietary USB byte arrays into
//! standard `TabletData` structures.

use hidapi::{HidApi, HidDevice};
use include_dir::{include_dir, Dir, DirEntry};
use std::collections::HashSet;
use std::fs;
use std::path::Path;
use std::time::{Duration, Instant};

pub mod config;
pub mod generic;
pub mod parsers;

use config::TabletConfiguration;
use generic::GenericNextTabletDriver;

/// The standardized output generated by any tablet parser.
/// Contains the decoded state of the pen for a specific millisecond in time.
#[derive(Debug, Clone, Default)]
pub struct TabletData {
    /// String representing the tool in use, generally "Pen" or "Eraser".
    pub status: String,
    /// Absolute raw X coordinate from the hardware sensor.
    pub x: u16,
    /// Absolute raw Y coordinate from the hardware sensor.
    pub y: u16,
    /// Absolute raw pressure value.
    pub pressure: u16,
    /// Pen tilt on the X axis (if supported).
    pub tilt_x: i8,
    /// Pen tilt on the Y axis (if supported).
    pub tilt_y: i8,
    /// Bitmask representing pressed barrel buttons (e.g., bit 0 = lower button).
    pub buttons: u8,
    /// True if the user flipped the pen to use the physical eraser nub.
    pub eraser: bool,
    /// Distance from the tablet surface (vendor specific, often 0).
    pub hover_distance: u8,
    /// The unparsed, raw hexadecimal byte array (used for the Debugger console).
    pub raw_data: String,
    /// Tracks whether the USB device is currently actively communicating.
    pub is_connected: bool,
}

/// Diagnostic statistics collected for the current session.
#[derive(Clone, Copy, Debug, Default)]
pub struct DriverStats {
    /// The current calculated physical hand speed (useful for analyzing drawing habits).
    pub handspeed: f32,
    /// Total aggregate distance the pen has traveled while active.
    pub total_distance_mm: f32,
}

/// The common interface that the input Engine uses to query device capabilities
/// and decode incoming byte arrays.
pub trait NextTabletDriver {
    /// Returns the human-readable marketing name of the tablet.
    fn get_name(&self) -> &str;
    /// Returns hardware resolution and max pressure: `(MaxX, MaxY, MaxPressure)`
    fn get_specs(&self) -> (f32, f32, f32);
    /// Returns physical tablet size in millimeters: `(Width, Height)`
    fn get_physical_specs(&self) -> (f32, f32);
    /// Returns the USB `(VendorID, ProductID)`.
    fn get_vid_pid(&self) -> (u16, u16);
    /// Attempts to parse a raw USB packet into standard `TabletData`.
    /// Returns `None` if the packet is malformed or empty.
    fn parse(&self, data: &[u8]) -> Option<TabletData>;
}

static TABLET_CONFIGS_DIR: Dir = include_dir!("$CARGO_MANIFEST_DIR/tablets");

lazy_static::lazy_static! {
    static ref LOADED_CONFIGS: Vec<TabletConfiguration> = load_configurations();
}

fn load_configurations() -> Vec<TabletConfiguration> {
    let mut configs = Vec::new();
    let mut loaded_names = HashSet::new();

    let local_dir = Path::new("tablets");
    if local_dir.exists() {
        load_from_disk_recursive(local_dir, &mut configs, &mut loaded_names);
    }

    load_embedded_recursive(&TABLET_CONFIGS_DIR, &mut configs, &mut loaded_names);
    configs
}

fn load_embedded_recursive(
    dir: &Dir,
    configs: &mut Vec<TabletConfiguration>,
    names: &mut HashSet<String>,
) {
    for entry in dir.entries() {
        match entry {
            DirEntry::Dir(sub_dir) => {
                load_embedded_recursive(sub_dir, configs, names);
            }
            DirEntry::File(file) => {
                if file.path().extension().and_then(|s| s.to_str()) == Some("json") {
                    if let Some(content_str) = file.contents_utf8() {
                        if let Ok(config) = serde_json::from_str::<TabletConfiguration>(content_str)
                        {
                            if !names.contains(&config.name) {
                                configs.push(config);
                            }
                        }
                    }
                }
            }
        }
    }
}

fn load_from_disk_recursive(
    path: &Path,
    configs: &mut Vec<TabletConfiguration>,
    names: &mut HashSet<String>,
) {
    if let Ok(entries) = fs::read_dir(path) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                load_from_disk_recursive(&p, configs, names);
            } else if p.extension().and_then(|s| s.to_str()) == Some("json") {
                if let Ok(content) = fs::read_to_string(&p) {
                    if let Ok(config) = serde_json::from_str::<TabletConfiguration>(&content) {
                        names.insert(config.name.clone());
                        configs.push(config);
                    }
                }
            }
        }
    }
}

pub fn detect_tablet(api: &HidApi) -> Option<(HidDevice, Box<dyn NextTabletDriver>, u16, u16)> {
    let global_start = Instant::now();
    let enum_start = Instant::now();
    let devices: Vec<_> = api.device_list().collect();
    let enum_duration = enum_start.elapsed();

    if enum_duration > Duration::from_millis(500) {
        log::warn!(target: "Detect", "HID Enumeration SLOW: {:.2?}", enum_duration);
    }

    let configs = &*LOADED_CONFIGS;

    for config in configs {
        for digitizer in &config.digitizer_identifiers {
            for device_info in &devices {
                if device_info.vendor_id() == digitizer.vendor_id
                    && device_info.product_id() == digitizer.product_id
                {
                    let interface = device_info.interface_number();
                    let open_start = Instant::now();

                    match api.open_path(device_info.path()) {
                        Ok(device) => {
                            let open_duration = open_start.elapsed();
                            let mut init_success = true;
                            use base64::{engine::general_purpose, Engine as _};

                            let init_start = Instant::now();

                            // Feature Reports
                            if let Some(reports) = &digitizer.feature_init_report {
                                for report_str in reports {
                                    if let Ok(data) = general_purpose::STANDARD.decode(report_str) {
                                        if let Err(e) = device.send_feature_report(&data) {
                                            log::error!(target: "Detect", "Init Error (Feature): {}", e);
                                            init_success = false;
                                            break;
                                        }
                                    }
                                }
                            }

                            // Output Reports
                            if init_success {
                                if let Some(reports) = &digitizer.output_init_report {
                                    for report_str in reports {
                                        if let Ok(data) =
                                            general_purpose::STANDARD.decode(report_str)
                                        {
                                            if let Err(e) = device.write(&data) {
                                                log::error!(target: "Detect", "Init Error (Output): {}", e);
                                                init_success = false;
                                                break;
                                            }
                                        }
                                    }
                                }
                            }

                            if !init_success {
                                continue;
                            }

                            log::info!(target: "Detect",
                                "{} | Enum: {:.2?} | Open: {:.2?} | Init: {:.2?} | Total: {:.2?}",
                                config.name, enum_duration, open_duration, init_start.elapsed(), global_start.elapsed()
                            );

                            return Some((
                                device,
                                Box::new(GenericNextTabletDriver::new(
                                    config.clone(),
                                    digitizer.vendor_id,
                                    digitizer.product_id,
                                )),
                                digitizer.vendor_id,
                                digitizer.product_id,
                            ));
                        }
                        Err(e) => {
                            log::trace!(target: "Detect", "Interface {} busy: {}", interface, e);
                        }
                    }
                }
            }
        }
    }
    None
}
