name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release EXE
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2

      - name: Build Rust Project
        run: cargo build --release

      - name: Compile Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: user_mode_dist/Tablet_Driver_Setup_x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}